export const collectionValidators = {
  users: {
    $jsonSchema: {
      bsonType: "object",
      required: [
        "_id",
        "email",
        "emailNormalized",
        "passwordHash",
        "createdAt",
        "updatedAt",
      ],
      properties: {
        _id: { bsonType: "objectId" },
        email: { bsonType: "string", minLength: 1 },
        emailNormalized: { bsonType: "string", minLength: 1 },
        passwordHash: { bsonType: "string", minLength: 1 },
        createdAt: { bsonType: "date" },
        updatedAt: { bsonType: "date" },
      },
    },
  },
  sessions: {
    $jsonSchema: {
      bsonType: "object",
      required: ["_id", "userId", "tokenHash", "expiresAt", "createdAt"],
      properties: {
        _id: { bsonType: "objectId" },
        userId: { bsonType: "objectId" },
        tokenHash: { bsonType: "string", minLength: 1 },
        expiresAt: { bsonType: "date" },
        createdAt: { bsonType: "date" },
      },
    },
  },
  orders: {
    $jsonSchema: {
      bsonType: "object",
      required: [
        "_id",
        "userId",
        "customer",
        "dueDate",
        "currency",
        "lines",
        "totalCents",
        "amountDueCents",
        "paymentCount",
        "version",
        "createdAt",
        "updatedAt",
      ],
      properties: {
        _id: { bsonType: "objectId" },
        userId: { bsonType: "objectId" },
        customer: { bsonType: "string", minLength: 1 },
        dueDate: { bsonType: "string", pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$" },
        currency: { enum: ["USD"] },
        lines: {
          bsonType: "array",
          minItems: 1,
          maxItems: 100,
          items: {
            bsonType: "object",
            required: ["id", "description", "quantity", "unitPriceCents"],
            properties: {
              id: { bsonType: "string", minLength: 1 },
              description: { bsonType: "string", minLength: 1 },
              quantity: { bsonType: "int", minimum: 1, maximum: 1_000_000 },
              unitPriceCents: { bsonType: "long", minimum: 0 },
            },
          },
        },
        totalCents: { bsonType: "long", minimum: 1 },
        amountDueCents: { bsonType: "long", minimum: 0 },
        paymentCount: { bsonType: "int", minimum: 0 },
        refundCount: { bsonType: "int", minimum: 0 },
        version: { bsonType: "int", minimum: 1 },
        createdAt: { bsonType: "date" },
        updatedAt: { bsonType: "date" },
      },
    },
  },
  payments: {
    $jsonSchema: {
      bsonType: "object",
      required: [
        "_id",
        "userId",
        "orderId",
        "sequence",
        "amountCents",
        "paymentDate",
        "idempotencyKey",
        "requestHash",
        "balanceBeforeCents",
        "balanceAfterCents",
        "recordedAt",
      ],
      properties: {
        _id: { bsonType: "objectId" },
        userId: { bsonType: "objectId" },
        orderId: { bsonType: "objectId" },
        sequence: { bsonType: "int", minimum: 1 },
        amountCents: { bsonType: "long", minimum: 1 },
        paymentDate: { bsonType: "string", pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$" },
        note: { bsonType: "string", maxLength: 1_000 },
        idempotencyKey: { bsonType: "string", minLength: 1 },
        requestHash: { bsonType: "string", minLength: 1 },
        balanceBeforeCents: { bsonType: "long", minimum: 0 },
        balanceAfterCents: { bsonType: "long", minimum: 0 },
        recordedAt: { bsonType: "date" },
      },
    },
  },
  auditEvents: {
    $jsonSchema: {
      bsonType: "object",
      required: ["_id", "userId", "orderId", "action", "details", "occurredAt"],
      properties: {
        _id: { bsonType: "objectId" },
        userId: { bsonType: "objectId" },
        orderId: { bsonType: "objectId" },
        action: { enum: ["PAYMENT_RECORDED", "REFUND_RECORDED"] },
        details: { bsonType: "object" },
        occurredAt: { bsonType: "date" },
      },
    },
  },
  refunds: {
    $jsonSchema: {
      bsonType: "object",
      required: [
        "_id",
        "userId",
        "orderId",
        "sequence",
        "amountCents",
        "refundDate",
        "idempotencyKey",
        "requestHash",
        "balanceBeforeCents",
        "balanceAfterCents",
        "recordedAt",
      ],
      properties: {
        _id: { bsonType: "objectId" },
        userId: { bsonType: "objectId" },
        orderId: { bsonType: "objectId" },
        sequence: { bsonType: "int", minimum: 1 },
        amountCents: { bsonType: "long", minimum: 1 },
        refundDate: { bsonType: "string", pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$" },
        note: { bsonType: "string", maxLength: 1_000 },
        idempotencyKey: { bsonType: "string", minLength: 1 },
        requestHash: { bsonType: "string", minLength: 1 },
        balanceBeforeCents: { bsonType: "long", minimum: 0 },
        balanceAfterCents: { bsonType: "long", minimum: 0 },
        recordedAt: { bsonType: "date" },
      },
    },
  },
} as const;
